import { Download, Eye, FileInput, LockKeyhole, Save, Scissors, Upload, X } from 'lucide-react';
import { useMemo, useRef, useState } from 'react';
import {
  CONFIDENCE_VALUES, EVIDENCE_QUALITY_VALUES, MANUAL_OPERATION_KINDS, MANUAL_STRING_MOTIONS, annotationsFromCsv, annotationsToCsv,
  canReveal, createBlindAnnotation, operationCategory, reviseAfterReveal, validateBlindDataset,
  type AnnotationPhase, type BlindDataset, type BlindReviewWindow, type ManualAnnotation, type OverlayDataset,
} from '../lib/operationAnnotationContract';

const panels = [
  { title: 'A · Depth', signals: ['measuredDepth', 'bitDepth'] }, { title: 'B · Hook', signals: ['hookHeight', 'hookLoad'] },
  { title: 'C · Mechanical', signals: ['rpm', 'wob', 'torque', 'rop'] }, { title: 'D · Hydraulics', signals: ['spp', 'qin'] },
  { title: 'E · Pumps', signals: ['spm1', 'spm2', 'spm3', 'totalSpm'] },
] as const;
const signalLabels: Record<string, string> = { measuredDepth: 'MeasuredDepth', bitDepth: 'BitDepth', hookHeight: 'HookHeight', hookLoad: 'HookLoad', rpm: 'RPM', wob: 'WOB', torque: 'Torque', rop: 'ROP', spp: 'SPP', qin: 'Qin', spm1: 'SPM1', spm2: 'SPM2', spm3: 'SPM3', totalSpm: 'TotalSpm' };

type Draft = { start: string; end: string; operation: typeof MANUAL_OPERATION_KINDS[number]; motion: typeof MANUAL_STRING_MOTIONS[number]; confidence: typeof CONFIDENCE_VALUES[number]; quality: typeof EVIDENCE_QUALITY_VALUES[number]; notes: string; transitionStart: string; transitionEnd: string; revisionReason: string; editIndex: number | null; };
const defaultDraft = (): Draft => ({ start: '', end: '', operation: 'Unknown', motion: 'Unknown', confidence: 'Ambiguous', quality: 'Limited', notes: '', transitionStart: '', transitionEnd: '', revisionReason: '', editIndex: null });

function readFile(file: File) { return file.text(); }
function download(name: string, text: string, type = 'text/csv') { const url = URL.createObjectURL(new Blob([text], { type })); const node = document.createElement('a'); node.href = url; node.download = name; node.click(); URL.revokeObjectURL(url); }
function status(annotations: ManualAnnotation[], review: BlindReviewWindow | undefined, revealed: boolean): AnnotationPhase {
  if (!review || !annotations.some((annotation) => annotation.reviewId === review.reviewId)) return 'UNLABELED';
  return revealed ? 'REVEALED' : 'BLIND_LABELED';
}

function TelemetryPanel({ review, signals, onRange }: { review: BlindReviewWindow; signals: readonly string[]; onRange: (start: string, end: string) => void }) {
  const [dragStart, setDragStart] = useState<number | null>(null);
  const frames = review.frames; const start = Date.parse(frames[0]?.timestamp || ''); const end = Date.parse(frames.at(-1)?.timestamp || '');
  const pick = (clientX: number, rect: DOMRect) => {
    const ratio = Math.max(0, Math.min(1, (clientX - rect.left) / Math.max(1, rect.width)));
    const nearest = frames.reduce((best, frame) => Math.abs(Date.parse(frame.timestamp) - (start + ratio * (end - start))) < Math.abs(Date.parse(best.timestamp) - (start + ratio * (end - start))) ? frame : best, frames[0]);
    return nearest?.timestamp || '';
  };
  return <section className="rounded-md border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-950">
    <div className="mb-2 flex items-center justify-between"><strong className="text-sm">{panels.find((panel) => panel.signals === signals)?.title}</strong><span className="text-[10px] text-slate-500">拖拽选择标注区间</span></div>
    <div className="grid gap-2" onPointerDown={(event) => setDragStart(event.clientX)} onPointerUp={(event) => { if (dragStart !== null) { const rect = event.currentTarget.getBoundingClientRect(); const a = pick(dragStart, rect); const b = pick(event.clientX, rect); onRange(a < b ? a : b, a < b ? b : a); } setDragStart(null); }}>
      {signals.map((signal) => <Sparkline key={signal} review={review} signal={signal} />)}
    </div>
  </section>;
}

function Sparkline({ review, signal }: { review: BlindReviewWindow; signal: string }) {
  const points = review.frames.map((frame, index) => ({ index, value: frame.signals[signal]?.value, available: frame.signals[signal]?.available, unit: frame.signals[signal]?.unit }));
  const known = points.filter((point) => point.available && point.value !== null) as Array<{ index: number; value: number; available: boolean; unit: string | null }>;
  const min = known.length ? Math.min(...known.map((point) => point.value)) : 0; const max = known.length ? Math.max(...known.map((point) => point.value)) : 1; const span = max - min || 1;
  const path = known.map((point, index) => `${index === 0 ? 'M' : 'L'} ${(point.index / Math.max(1, points.length - 1)) * 100} ${34 - ((point.value - min) / span) * 28}`).join(' ');
  return <div className="rounded border border-slate-100 bg-slate-50 px-2 py-1 dark:border-slate-800 dark:bg-slate-900"><div className="flex justify-between text-[10px]"><span>{signalLabels[signal]}</span><span>{known.length ? `${known.at(-1)?.value?.toFixed(3)} ${known.at(-1)?.unit || ''}` : 'unavailable'}</span></div><svg viewBox="0 0 100 38" preserveAspectRatio="none" className="h-10 w-full"><path d={path} fill="none" stroke="#0891b2" strokeWidth="1.25" vectorEffect="non-scaling-stroke" /></svg></div>;
}

export default function OperationAnnotation() {
  const [dataset, setDataset] = useState<BlindDataset | null>(null); const [overlay, setOverlay] = useState<OverlayDataset | null>(null); const [annotations, setAnnotations] = useState<ManualAnnotation[]>([]);
  const [index, setIndex] = useState(0); const [revealed, setRevealed] = useState(false); const [draft, setDraft] = useState<Draft>(defaultDraft); const [annotatorId, setAnnotatorId] = useState(''); const [message, setMessage] = useState('导入 blind dataset 开始。'); const overlayInput = useRef<HTMLInputElement>(null);
  const review = dataset?.reviewWindows[index]; const reviewAnnotations = annotations.filter((annotation) => annotation.reviewId === review?.reviewId); const phase = status(annotations, review, revealed);
  const currentOverlay = useMemo(() => overlay?.reviewWindows.find((item) => item.reviewId === review?.reviewId), [overlay, review?.reviewId]);
  const update = <K extends keyof Draft>(key: K, value: Draft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const selectRange = (start: string, end: string) => { update('start', start); update('end', end); };
  const loadBlind = async (file?: File) => { if (!file) return; try { const parsed = validateBlindDataset(JSON.parse(await readFile(file))); setDataset(parsed); setOverlay(null); setAnnotations([]); setIndex(0); setRevealed(false); setDraft(defaultDraft()); setMessage(`已加载 ${parsed.reviewWindows.length} 个盲审窗口；模型 overlay 未加载。`); } catch (error) { setMessage(error instanceof Error ? error.message : '加载失败。'); } };
  const loadOverlay = async (file?: File) => { if (!file) return; if (!review || !canReveal(review.reviewId, annotations)) { setMessage('必须先保存当前窗口的 blind label，才允许导入 overlay。'); return; } try { const parsed = JSON.parse(await readFile(file)) as OverlayDataset; if (!Array.isArray(parsed.reviewWindows)) throw new Error('overlay 格式无效。'); setOverlay(parsed); setMessage('overlay 已导入，但仍需点击 Reveal Comparison 才显示。'); } catch (error) { setMessage(error instanceof Error ? error.message : 'overlay 加载失败。'); } };
  const save = () => { if (!review || !annotatorId.trim() || !draft.start || !draft.end) { setMessage('请填写 AnnotatorId，并通过拖拽或时间选项选择 SegmentStart/End。'); return; } const input = { reviewId: review.reviewId, annotatorId: annotatorId.trim(), eventKey: review.eventKey, windowStart: review.windowStart, windowEnd: review.windowEnd, segmentStart: draft.start, segmentEnd: draft.end, manualOperationKind: draft.operation, manualStringMotion: draft.motion, confidence: draft.confidence, evidenceQuality: draft.quality, transitionIntervalStart: draft.transitionStart, transitionIntervalEnd: draft.transitionEnd, notes: draft.notes, sourceVersion: dataset?.sourceVersion || '', annotationVersion: dataset?.annotationVersion || '' };
    try { const next = [...annotations]; if (draft.editIndex !== null) { const previous = reviewAnnotations[draft.editIndex]; if (!previous) return; const changed = revealed ? reviseAfterReveal(previous, { ...input, manualOperationKind: draft.operation, manualStringMotion: draft.motion, confidence: draft.confidence, evidenceQuality: draft.quality, notes: draft.notes, segmentStart: draft.start, segmentEnd: draft.end }, draft.revisionReason) : { ...previous, ...input, manualOperationCategory: operationCategory(draft.operation) }; next[next.indexOf(previous)] = changed; } else next.push(createBlindAnnotation(input)); setAnnotations(next); setDraft(defaultDraft()); setMessage(revealed ? '修改已标记为 PostRevealRevision。' : 'Blind label 已保存；现在可加载并 reveal comparison。'); } catch (error) { setMessage(error instanceof Error ? error.message : '保存失败。'); } };
  const edit = (annotation: ManualAnnotation) => { const local = reviewAnnotations.indexOf(annotation); setDraft({ start: annotation.segmentStart, end: annotation.segmentEnd, operation: annotation.manualOperationKind, motion: annotation.manualStringMotion, confidence: annotation.confidence, quality: annotation.evidenceQuality, notes: annotation.notes, transitionStart: annotation.transitionIntervalStart, transitionEnd: annotation.transitionIntervalEnd, revisionReason: '', editIndex: local }); };
  const remove = (annotation: ManualAnnotation) => setAnnotations((current) => current.filter((item) => item !== annotation));
  const split = (annotation: ManualAnnotation) => { const a = Date.parse(annotation.segmentStart); const b = Date.parse(annotation.segmentEnd); if (!Number.isFinite(a) || !Number.isFinite(b) || b - a < 2000) return; const middle = new Date((a + b) / 2).toISOString(); const left = { ...annotation, segmentEnd: middle }; const right = { ...annotation, segmentStart: middle, createdAt: new Date().toISOString() }; setAnnotations((current) => current.flatMap((item) => item === annotation ? [left, right] : [item])); };
  const mergeWithNext = (annotation: ManualAnnotation, next: ManualAnnotation | undefined) => { if (!next || annotation.manualOperationKind !== next.manualOperationKind || annotation.manualStringMotion !== next.manualStringMotion) { setMessage('只能合并相邻且 Operation Kind / String Motion 相同的 segments。'); return; } setAnnotations((current) => current.filter((item) => item !== annotation && item !== next).concat({ ...annotation, segmentStart: annotation.segmentStart < next.segmentStart ? annotation.segmentStart : next.segmentStart, segmentEnd: annotation.segmentEnd > next.segmentEnd ? annotation.segmentEnd : next.segmentEnd, createdAt: new Date().toISOString() })); };
  const downloadAnnotations = () => download('operation_annotation_annotations_v1.csv', annotationsToCsv(annotations));
  const importAnnotations = async (file?: File) => { if (!file) return; try { setAnnotations(annotationsFromCsv(await readFile(file))); setMessage('annotation CSV 已导入；pre-reveal records 保持原始内容。'); } catch (error) { setMessage(error instanceof Error ? error.message : 'annotation CSV 导入失败。'); } };
  return <main className="mx-auto max-w-[1600px] space-y-4 p-4 md:p-6">
    <header className="rounded-lg border border-violet-300 bg-violet-50 p-4 text-violet-950 dark:border-violet-800 dark:bg-violet-950/30 dark:text-violet-100"><div className="flex flex-wrap items-center gap-2"><LockKeyhole className="h-5 w-5" /><strong>RESEARCH · MANUAL ANNOTATION</strong><span className="rounded bg-violet-700 px-2 py-0.5 text-xs text-white">NOT ALARM INPUT</span></div><p className="mt-1 text-sm">此工作区只生成离线人工 ground truth；不会读取或写入正式报警、Reference、Evidence 或 Candidate。</p></header>
    <section className="flex flex-wrap items-center gap-2 rounded-md border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-950"><label className="ops-button-secondary flex cursor-pointer items-center gap-2 px-3 py-2 text-sm"><FileInput className="h-4 w-4" />导入 Blind Dataset<input className="hidden" type="file" accept="application/json" onChange={(event) => void loadBlind(event.target.files?.[0])} /></label><label className="ops-button-secondary flex cursor-pointer items-center gap-2 px-3 py-2 text-sm"><Upload className="h-4 w-4" />导入 Annotation CSV<input className="hidden" type="file" accept="text/csv" onChange={(event) => void importAnnotations(event.target.files?.[0])} /></label><button type="button" className="ops-button-secondary flex items-center gap-2 px-3 py-2 text-sm" onClick={downloadAnnotations} disabled={!annotations.length}><Download className="h-4 w-4" />导出 Annotation CSV</button><input value={annotatorId} onChange={(event) => setAnnotatorId(event.target.value)} placeholder="AnnotatorId" className="rounded border border-slate-300 px-2 py-2 text-sm dark:border-slate-700 dark:bg-slate-900" /><span className="text-xs text-slate-500">{message}</span></section>
    {!review ? <div className="rounded-md border border-dashed border-slate-300 p-10 text-center text-slate-500">请导入 operation_annotation_dataset_v1.json。Reveal overlay 必须在保存 blind label 后单独导入。</div> : <div className="grid gap-4 xl:grid-cols-[220px_minmax(0,1fr)_340px]">
      <aside className="space-y-2 rounded-md border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-950"><div className="text-sm font-medium">Review progress</div><div className="text-2xl font-semibold">{index + 1} / {dataset?.reviewWindows.length}</div><div className="rounded bg-slate-100 px-2 py-1 text-xs dark:bg-slate-900">{review.reviewId} · {phase}</div><div className="max-h-[64vh] space-y-1 overflow-auto">{dataset?.reviewWindows.map((item, itemIndex) => <button key={item.reviewId} type="button" onClick={() => { setIndex(itemIndex); setRevealed(false); setDraft(defaultDraft()); }} className={`w-full rounded px-2 py-1.5 text-left text-xs ${itemIndex === index ? 'bg-cyan-100 text-cyan-950 dark:bg-cyan-950/50 dark:text-cyan-100' : 'hover:bg-slate-100 dark:hover:bg-slate-900'}`}>{item.reviewId} {annotations.some((annotation) => annotation.reviewId === item.reviewId) ? '✓' : ''}</button>)}</div></aside>
      <section className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="text-xs text-slate-500">Blind mode · raw admitted telemetry</div><h1 className="text-xl font-semibold">{review.reviewId}</h1></div><div className="flex gap-2"><label className="ops-button-secondary flex cursor-pointer items-center gap-1 px-2 py-1.5 text-xs"><Upload className="h-3.5 w-3.5" />导入 Reveal Overlay<input ref={overlayInput} className="hidden" type="file" accept="application/json" onChange={(event) => void loadOverlay(event.target.files?.[0])} /></label><button type="button" className="ops-button-secondary flex items-center gap-1 px-2 py-1.5 text-xs" disabled={!overlay || !canReveal(review.reviewId, annotations)} onClick={() => setRevealed(true)}><Eye className="h-3.5 w-3.5" />Reveal Comparison</button></div></div>
        <div className="grid gap-3">{panels.map((panel) => <TelemetryPanel key={panel.title} review={review} signals={panel.signals} onRange={selectRange} />)}</div>
        {revealed && currentOverlay ? <section className="rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-100"><strong>REVEALED · comparison overlay</strong><div className="mt-2 grid gap-2 md:grid-cols-2"><span>V1: {currentOverlay.frames.at(-1)?.v1FineLabel}</span><span>StepDelta: {currentOverlay.frames.at(-1)?.controlConfirmedFineLabel}</span><span>AnchoredNet: {currentOverlay.frames.at(-1)?.anchoredConfirmedFineLabel}</span><span>Recorded ACTCOD: {currentOverlay.frames.at(-1)?.recordedActcod || 'missing'}</span><span>PumpGate: {currentOverlay.frames.at(-1)?.pumpGateStatus || 'missing'}</span><span>Motion basis: {currentOverlay.frames.at(-1)?.motionConfirmationBasis}</span></div></section> : null}
      </section>
      <aside className="space-y-3 rounded-md border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-950"><div className="text-sm font-medium">Manual Segment</div><TimeSelect label="Segment start" value={draft.start} frames={review.frames} onChange={(value) => update('start', value)} /><TimeSelect label="Segment end" value={draft.end} frames={review.frames} onChange={(value) => update('end', value)} />
        <Select label="Operation kind" value={draft.operation} values={MANUAL_OPERATION_KINDS} onChange={(value) => update('operation', value as Draft['operation'])} /><Select label="String motion" value={draft.motion} values={MANUAL_STRING_MOTIONS} onChange={(value) => update('motion', value as Draft['motion'])} /><Select label="Confidence" value={draft.confidence} values={CONFIDENCE_VALUES} onChange={(value) => update('confidence', value as Draft['confidence'])} /><Select label="Evidence quality" value={draft.quality} values={EVIDENCE_QUALITY_VALUES} onChange={(value) => update('quality', value as Draft['quality'])} />
        <TimeSelect label="Transition interval start (optional)" value={draft.transitionStart} frames={review.frames} onChange={(value) => update('transitionStart', value)} optional /><TimeSelect label="Transition interval end (optional)" value={draft.transitionEnd} frames={review.frames} onChange={(value) => update('transitionEnd', value)} optional />
        {revealed && draft.editIndex !== null ? <input value={draft.revisionReason} onChange={(event) => update('revisionReason', event.target.value)} placeholder="RevisionReason required after reveal" className="w-full rounded border border-amber-300 px-2 py-1.5 text-xs dark:bg-slate-900" /> : null}<textarea value={draft.notes} onChange={(event) => update('notes', event.target.value)} placeholder="Notes: raw telemetry evidence only" className="min-h-20 w-full rounded border border-slate-300 p-2 text-xs dark:border-slate-700 dark:bg-slate-900" />
        <button type="button" className="ops-button-primary flex w-full items-center justify-center gap-2 px-3 py-2 text-sm" onClick={save}><Save className="h-4 w-4" />{draft.editIndex === null ? 'Save blind label' : 'Save edit'}</button><div className="space-y-2 border-t border-slate-200 pt-3 dark:border-slate-700">{reviewAnnotations.map((annotation, annotationIndex) => <div key={`${annotation.createdAt}-${annotation.segmentStart}`} className="rounded bg-slate-50 p-2 text-xs dark:bg-slate-900"><div className="font-medium">{annotation.manualOperationKind} · {annotation.manualStringMotion}</div><div>{annotation.segmentStart} → {annotation.segmentEnd}</div><div className="mt-1 flex gap-2"><button type="button" onClick={() => edit(annotation)}>edit</button><button type="button" onClick={() => split(annotation)}><Scissors className="inline h-3 w-3" /> split</button><button type="button" onClick={() => mergeWithNext(annotation, reviewAnnotations[annotationIndex + 1])}>merge next</button><button type="button" onClick={() => remove(annotation)}><X className="inline h-3 w-3" /> delete</button></div></div>)}</div>
      </aside>
    </div>}
  </main>;
}

function TimeSelect({ label, value, frames, onChange, optional = false }: { label: string; value: string; frames: BlindReviewWindow['frames']; onChange: (value: string) => void; optional?: boolean }) { return <label className="block text-xs"><span className="mb-1 block text-slate-500">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded border border-slate-300 px-2 py-1.5 dark:border-slate-700 dark:bg-slate-900"><option value="">{optional ? 'not specified' : 'select from chart'}</option>{frames.map((frame) => <option key={frame.timestamp} value={frame.timestamp}>{frame.timestamp}</option>)}</select></label>; }
function Select({ label, value, values, onChange }: { label: string; value: string; values: readonly string[]; onChange: (value: string) => void }) { return <label className="block text-xs"><span className="mb-1 block text-slate-500">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded border border-slate-300 px-2 py-1.5 dark:border-slate-700 dark:bg-slate-900">{values.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>; }
